### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'One' and 'MutableDenseMatrix'

### ISSUE THREAD

**Issue by lzs201522** [istoony/winograd-convolutional-nn#4]
dear my friend , i run the calcMx.py and failed to get the result, here is the corrupt code:
Traceback (most recent call last):
  File "D:\winograd-convolutional-nn-master\calcMx.py", line 211, in <module>
    showCookToomFilter(ip , n, r)
  File "D:\winograd-convolutional-nn-master\calcMx.py", line 119, in showCookToomFilter
    AT,G,BT,f = cookToomFilter(a,n,r,fractionsIn)
  File "D:\winograd-convolutional-nn-master\calcMx.py", line 63, in cookToomFilter
    G = (A(a,alpha,r).T/f).T
  File "C:\ProgramData\Anaconda3\envs\tf_212\lib\site-packages\sympy\core\decorators.py", line 106, in binary_op_wrapper
    return func(self, other)
  File "C:\ProgramData\Anaconda3\envs\tf_212\lib\site-packages\sympy\matrices\common.py", line 2660, in __truediv__
    return self * (self.one / other)
TypeError: unsupported operand type(s) for /: 'One' and 'MutableDenseMatrix'
I 'd like to know how to fix it, or you python's version

**Comment by zhouyecs** [comment]
calcMx.py seems to be modified from https://github.com/andravin/wincnn/blob/master/wincnn.py, you can refer wincnn.py
